### PR TITLE
Fix/dont display 0

### LINKED ISSUE #64: fix: Token balances should never display as "0" when loading
It's confusing and not correct
For example: https://gyazo.com/38504d43a5f36792f0211025d204d5ab

### PR DESCRIPTION
**Pull request by 0xtrooper**

### CODE REVIEW

File: src/pages/index.tsx [hunk 1]
```diff
@@ -95,23 +95,11 @@ const Home: NextPage = () => {
     changeTokenApproved(Number(tokenAllowances[i]) > Number(fromDetails.amount));
   }, [fromDetails.symbol]);
 
-  useEffect(() => {
```
Comment (crazysupercoder) [inline src/pages/index.tsx:98]: Is there any reason that you removed the calculation of swap rate?

Comment (0xtrooper) [reply src/pages/index.tsx:98]: ~~see this commit: https://github.com/ZigZagExchange/mammoth_UI/pull/65/commits/703ae076b693387602b74635c4955ff0671d1779 We allready call getSwapAmount in 'predictSwapResult'. These both get called at the same time and request the same external information. Merged them to only call StarkNet once (less requests - they impose a rather low ratelimt)~~

Comment (0xtrooper) [reply src/pages/index.tsx:98]: updated with https://github.com/ZigZagExchange/mammoth_UI/pull/65/commits/04ca13433eed157e2c764e1e90977e2d603eac2a

**Review by crazysupercoder — APPROVED** [review]
